name: Coverage
on: [push]
- push
- pull_request
permissions:
  contents: read
jobs:
  build_java_8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
        - 8
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
    - run: sudo apt update
    - run: sudo apt install inotify-tools
    - run: inotifywait -mr /home/runner/work/commons-lang/commons-lang/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
    - run: touch starting_buildjava8_uses-checkout_15
    - run: rm starting_buildjava8_uses-checkout_15
    - uses: actions/checkout@v3.0.2
    - run: touch starting_buildjava8_uses-cache_16
    - run: rm starting_buildjava8_uses-cache_16
    - uses: actions/cache@v3.0.8
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: '${{ runner.os }}-maven-

          '
    - run: touch starting_buildjava8_SetupJDKmatrixjava_23
    - run: rm starting_buildjava8_SetupJDKmatrixjava_23
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - run: touch starting_buildjava8_BuildwithMaven_28
    - run: rm starting_buildjava8_BuildwithMaven_28
    - name: Build with Maven
      run: mvn -V test jacoco:report --file pom.xml --no-transfer-progress
    - run: touch starting_buildjava8_UploadcoveragetoCodecov_30
    - run: rm starting_buildjava8_UploadcoveragetoCodecov_30
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./target/site/jacoco/jacoco.xml
    - run: touch starting_finished_finished_8979874
      if: always()
    - run: rm starting_finished_finished_8979874
      if: always()
    - name: Execute py script # run file
      if: always()
      run: |
        python .github/workflows/script.py
    - name: Pushes analysis to another repository
      if: always()
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'optimizing-ci-builds-ci-analysis'
        destination-github-username: 'UT-SE-Research'
        destination-repository-name: 'ci-analyzes'
        target-branch: '1675896667'
        target-directory: 'commons-lang/.github/workflows/coverage/buildjava8'

