# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Java CI

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        java: [ 8, 11, 17 ]
        experimental: [false]
#        include:
#          - java: 18-ea
#            experimental: true        
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
    - run: sudo apt update
    - run: sudo apt install inotify-tools
    - run: inotifywait -mr /home/runner/work/commons-lang/commons-lang/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'optimizing-ci-builds'
    - run: touch starting_build_uses-checkout_36
    - run: rm starting_build_uses-checkout_36
    - uses: actions/checkout@v3.0.2
    - run: touch starting_build_uses-cache_37
    - run: rm starting_build_uses-cache_37
    - uses: actions/cache@v3.0.8
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - run: touch starting_build_SetupJDKmatrixjava_43
    - run: rm starting_build_SetupJDKmatrixjava_43
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'      
        java-version: ${{ matrix.java }}
    - run: touch starting_build_BuildwithMaven_48
    - run: rm starting_build_BuildwithMaven_48
    - name: Build with Maven
      run: mvn -V -Ddoclint=all --file pom.xml --no-transfer-progress
    - run: touch starting_finished_finished_8979874
      if: always()
    - run: rm starting_finished_finished_8979874
      if: always()
    - name: rat check
      if: always()
      run: |
         if [ -f /home/runner/work/commons-lang/commons-lang/target/rat.txt ]; then cat /home/runner/work/commons-lang/commons-lang/target/rat.txt; fi
    - name: Check script file exists and execute
      if: always()
      run: |
        [ -f .github/workflows/script.py ] && python .github/workflows/script.py
        [ -f /home/runner/work/commons-lang/commons-lang/optimizing-ci-builds-ci-analysis/job.csv ] || mkdir -p /home/runner/work/commons-lang/commons-lang/optimizing-ci-builds-ci-analysis/; echo "${GITHUB_RUN_ID},${GITHUB_JOB},commons-lang,${GITHUB_WORKFLOW}" > /home/runner/work/commons-lang/commons-lang/optimizing-ci-builds-ci-analysis/job.csv
    - name: Checkout to destination CI-analyzes repo
      uses: actions/checkout@v3
      if: always()
      with:
        path: commons-lang
        ref: '1686780564-548a464'
        repository: 'UT-SE-Research/ci-analyzes'
        token: '${{ secrets.API_TOKEN_GITHUB }}'
        persist-credentials: true
    - name: Copy files to push to another directory
      if: always()
      run: |
        mkdir -p commons-lang/commons-lang/.github/workflows/maven/build_java_${{ matrix.java }}_experimental_${{ matrix.experimental }}
        cp -rvT optimizing-ci-builds-ci-analysis commons-lang/commons-lang/.github/workflows/maven/build_java_${{ matrix.java }}_experimental_${{ matrix.experimental }}
    - run: echo https://github.com/UT-SE-Research/ci-analyzes/tree/1686780564-548a464/commons-lang/.github/workflows/maven/build_java_${{ matrix.java }}_experimental_${{ matrix.experimental }}
    - name: Pushes analysis to another repository
      if: always()
      working-directory: commons-lang
      run: |
        commit_message=$GITHUB_REPOSITORY@$GITHUB_WORKFLOW_SHA
        git config --global user.name 'UT-SE-Research'
        git config --global user.email '${{ secrets.EMAIL }}'
        git add .
        git commit -m $commit_message
        while ! git push origin 1686780564-548a464; do
          git pull --rebase origin 1686780564-548a464
          sleep $((RANDOM % 5 + 1))
        done
