# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Java CI

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        java: [ 8, 11, 17 ]
        experimental: [false]
#        include:
#          - java: 18-ea
#            experimental: true        
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
    - run: sudo apt update
    - run: sudo apt install inotify-tools
    - run: inotifywait -mr /home/runner/work/commons-lang/commons-lang/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'optimizing-ci-builds'
    - run: touch starting_build_uses-checkout_36
    - run: rm starting_build_uses-checkout_36
    - uses: actions/checkout@v3.0.2
    - run: touch starting_build_uses-cache_37
    - run: rm starting_build_uses-cache_37
    - uses: actions/cache@v3.0.8
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - run: touch starting_build_SetupJDKmatrixjava_43
    - run: rm starting_build_SetupJDKmatrixjava_43
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'      
        java-version: ${{ matrix.java }}
    - run: touch starting_build_BuildwithMaven_48
    - run: rm starting_build_BuildwithMaven_48
    - name: Build with Maven
      run: mvn -V -Ddoclint=all --file pom.xml --no-transfer-progress
    - run: touch starting_finished_finished_8979874
      if: always()
    - run: rm starting_finished_finished_8979874
      if: always()
    - name: Execute py script # run file
      if: always()
      run: |
        echo pwd
        ls -la
        python .github/workflows/script.py
    - name: Pushes analysis to another repository
      if: always()
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'optimizing-ci-builds-ci-analysis'
        destination-github-username: 'UT-SE-Research'
        destination-repository-name: 'ci-analyzes'
        target-branch: '1676919400-c0ae930'
        target-directory: 'commons-lang/.github/workflows/maven/build_java_${{ matrix.java }}_experimental_${{ matrix.experimental }}'
      continue-on-error: true
    - name: Check push directory exit code
      if: steps.push_directory.outcome == 'failure'
      run: |
        echo 'push failed, trying pull and then push'
        git config --global user.name 'UT-SE-Research'
        git add .
        git commit -m 'rebased and pushed ${{ github.head_ref }}'
        while ! git push origin {time}; do
          git pull --rebase https://github.com/UT-SE-Research/ci-analyzes.git 1676919400-c0ae930
          git push https://UT-SE-Research:${ secrets.API_TOKEN_GITHUB }@github.com/UT-SE-Research/ci-analyzes.git HEAD:1676919400-c0ae930
        done
